server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://198.192.0.1:3306/user?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 120000
  redis:
    host: 198.192.0.1
    port: 6379
    password: 123456
  thymeleaf:
    cache: false


logging:
  level:
    com:
      example: debug
